name: Test node with worklows
on: push
jobs:
  first-job:
    name: Build with Node
    runs-on: ubuntu-latest
    container: node:12.22.12
    steps:
      - run: node --version
      - run: npm --version
